#!/bin/bash

application-version-set $(snap list microsample | tail -1 | awk '{print $2}')

# SNAP_ADDRESS=$(snap get microsample address)
# SNAP_PORT=$(snap get microsample port)
PORT=$(config-get port)
ADDRESS=$(unit-get private-address)

status=$(curl --silent ${ADDRESS}:${PORT} 2>&1 /dev/null)

if [ "$status" == "Online" ]; then
  status-set active "Service: $status"
else
  status-set waiting  "Service not Online."
fi
