#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

status-set maintenance "Upgrading charm."

./hooks/install

./hooks/config-changed

systemctl restart snap.microsample.microsample.service

# Wait a few sec so to let service start...
sleep 3

./hooks/update-status
