#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT modified its settings
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list


address=$(unit-get private-address)
port=$(config-get port)

relation-set hostname=$address
relation-set port=$port
# relation-set service_name="microsample_service"
