#!/bin/bash
set -e
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT joined

address=$(unit-get private-address)
port=$(config-get port)

## This is expected by the http interface
relation-set hostname=$address
relation-set port=$port

## This is specific for haproxy
relation-set service_name="microsample"
