#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT modified its settings
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list


address=$(unit-get private-address)
port=$(config-get port)
unitid=$(basename $JUJU_UNIT_NAME)

relation-set hostname=$address

relation-set port=$port

###################################################################### 
## If you use with haproxy and want setting coming from the relation: 
##
##    Uncomment this to send this over the relation
##    haproxy then ignore juju config haproxy services="..."
##
######################################################################
#relation-set "services=
#- { service_name: microsample,
#    service_host: 0.0.0.0,
#    service_port: 443,
#    service_options: [mode http, balance leastconn, http-check expect rstring ^Online$],
#    servers: [[microsample_unit_${unitid}, $address, $port, check]]}
#"
